### ISSUE TITLE
this NDArray implementation does not currently support this operation

### ISSUE THREAD

**Issue by leezea** [deepjavalibrary/djl#1409] opened 2021-12-09 03:18 UTC
## Description
when i run the jupyter/onnxruntime/machine_learning_with_ONNXRuntime in spark, if i run it in spark_local modle with command "spark-submit --class org.example.pro1.Test iris_test.jar" that is ok,
but when i run it in  spark_yarn model with commad "spark-submit --queue tst --master yarn --executor-memory 20g --driver-memory 20g --executor-cores 4 --num-executors 4 --class org.example.pro1.Test iris_test.jar"  ,the error appares like this "Caused by: java.lang.UnsupportedOperationException: This NDArray implementation does not currently support this operation"
why this appends? thanks for your reply!
my pom.xml like this :
  <properties>
    <spark.version>2.2.0</spark.version>
    <scala.version>2.11</scala.version>
    <maven.version>3.6.3</maven.version>
    <java.version>1.8</java.version>
  </properties>

  <dependencies>
        <dependency>
          <groupId>ai.djl.hadoop</groupId>
          <artifactId>hadoop</artifactId>
          <version>0.12.0</version>
        </dependency>

    
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>2.11.8</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.scalanlp</groupId>
      <artifactId>breeze_2.11</artifactId>
      <version>0.12</version>
    </dependency>
    <dependency>
      <groupId>org.scalanlp</groupId>
      <artifactId>breeze-viz_2.11</artifactId>
      <version>0.12</version>
    </dependency>

    
    <dependency>
      <groupId>ai.djl</groupId>
      <artifactId>api</artifactId>
      <version>0.12.0</version>
    </dependency>
    <dependency>
      <groupId>ai.djl.onnxruntime</groupId>
      <artifactId>onnxruntime-engine</artifactId>
      <version>0.12.0</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.onnxruntime</groupId>
      <artifactId>onnxruntime</artifactId>
      <version>1.4.0</version>
    </dependency>

    
    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-engine</artifactId>
      <version>0.12.0</version>
    </dependency>
    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-model-zoo</artifactId>
      <version>0.12.0</version>
    </dependency>
    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-native-auto</artifactId>
      <version>1.8.1</version>
    </dependency>
    <dependency>
      <groupId>net.java.dev.jna</groupId>
      <artifactId>jna</artifactId>
      <version>5.3.0</version>
    </dependency>
...
  <dependencies>

**Comment by frankfliu** [comment] 2021-12-09 04:01
@leezea Can you try 0.14.0?

OnnxRuntime itself doesn't support NDArray operations, it rely on PyTorch engine to do it. We made some changes in HyBird engine implementation in 0.13.0. Please see if the issue is fixed in latest version.

**Comment by leezea** [comment] 2021-12-09 09:07
hanks for your reply!
my system is ubuntu16, 
if i using the version like 13 or 14, there will appare on error ,like " /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found" ,i can install it to fix this bug, 
but still another like "/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found",look like it not support in ubuntu16?
so this meaning i cannot using 13 or 14 on ubuntu16, i can change an other high system like ubuntu18,but the yarn system is ubuntu16, which means i cannot using djl on it?

**Comment by frankfliu** [comment] 2021-12-09 16:23
@leezea Your error is not related to DJL, it's linux glibc version issue:
1. ubuntu 16.04 is end of life already, many of the engine dropped 16.04 support already, we don't recommend to use 16.04 any more
2. If you are using PyTorch, we have pre-cxx11 native package that can run on lower version of glibc system, see: https://docs.djl.ai/engines/pytorch/pytorch-engine/index.html#for-pre-cxx11-build

**Comment by siddvenk** [comment] 2022-11-09 20:41
Closing due to inactivity. Please reopen if you still have questions.

**Closed by siddvenk** 2022-11-09 20:41 UTC
Labels: enhancement
