### ISSUE TITLE
Mxnet 1.6 The calculation result of the model is incorrect.（Mxnet 1.6 版本，模型计算结果不正确）

### ISSUE THREAD

**Issue by fierceX** [deepjavalibrary/djl#1731] opened 2022-06-20 07:54 UTC
## Description

通过Gluon导出的模型，在DJL上加载后，计算结果不正确。
After loading the model derived through Gluon on DJL, the calculation result is incorrect.

在Python中的结果：
Results in Python：
<img width="393" alt="截屏2022-06-20 14 54 19" src="https://user-images.githubusercontent.com/13912058/174551578-ef40d1e5-c73c-47ec-a6fa-7ee3ed57087a.png">

在DJL中的结果：
Results in DJL：
<img width="525" alt="截屏2022-06-22" src="https://user-images.githubusercontent.com/13912058/174551893-49539c24-86bf-426b-856b-eae3024f2a7e.png">

Python Code：
```python
import mxnet as mx
from mxnet import nd,gluon
net = mx.gluon.SymbolBlock.imports('./symmodel/xc-symbol.json',['data0','data1'],'./symmodel/xc-0000.params')

a = nd.array([3,1118,254,0,2]).reshape((1,-1))
print(net(a,nd.ones((1,24))))
```

Scala Code：
```scala
class NerTranslator() extends Translator[List[String],List[String]]{
    override def processInput(ctx: TranslatorContext, input: List[String]): NDList = {
      val manager = ctx.getNDManager
      var ndlist: List[NDArray] = List()

      //输入 3,1118,254,0,2
      val input_int = Array(3,1118,254,0,2)
      val ndArray = manager.create(input_int)
      ndlist = ndlist :+ ndArray
      
      val ins = NDArrays.stack(new NDList(ndlist.asJava))

      var vvars_ndarry = manager.full(new Shape(1,24),1,DataType.FLOAT32)
      var ndlists: List[NDArray] = List()
      ndlists = ndlists :+ ins
      ndlists = ndlists :+ vvars_ndarry

      new NDList(ndlists.asJava)
    }

    override def processOutput(ctx: TranslatorContext, list: NDList): List[String] = {
      val result = list.singletonOrThrow()
      //输出
      println(result.toArray().mkString(",,"))
      var rr:List[String] =  List()
      rr
    }

    override def getBatchifier: Batchifier = null
  }

object Main {
  def main(args: Array[String]){
      var input_txt:List[String] = List()
      input_txt = "aaaa" :: input_txt

      var modelDir = Paths.get("symmodel")
      var model = Model.newInstance("symmodel")
      model.load(modelDir, "xc")
      val tran = new NerTranslator()
      val predictor = model.newPredictor(tran)
      val result = predictor.predict(input_txt)
    println("OK")
  }
}
```

[ner.zip](https://github.com/deepjavalibrary/djl/files/8938643/ner.zip)

**Comment by lanking520** [comment] 2022-06-20 17:47
Taking a look now

**Comment by lanking520** [comment] 2022-06-20 20:33
I am able to reproduce python result matching what Java have:

```
import mxnet as mx
from mxnet import nd,gluon
net = mx.gluon.SymbolBlock.imports('./symmodel/xc-symbol.json',['data0','data1'],'./symmodel/xc-0000.params')

# add this to match DJL config
net.hybridize(static_alloc=True, static_shape=True)

a = nd.array([3,1118,254,0,2]).reshape((1,-1))
print(net(a,nd.ones((1,24))))
```

Looks like you have not enable `net.hybridize(static_alloc=True, static_shape=True)` during model saving after training. Please try to add this line before you export the model to symbol. In the meantime, I will work on a DJL solution to disable these two options before loading.

**Comment by lanking520** [comment] 2022-06-20 21:22
I raised a PR to fix your issue. It will be part of DJL 0.18.0. You can try our nightly snapshot once the PR is merged.

**Closed** 2022-06-21 01:54 UTC
Labels: bug
