### ISSUE TITLE
PtNDArray memory leak，ai.djl.pytorch.jni.PyTorchLibrary#torchIndexInit don't have matching method to delete index

### ISSUE THREAD

**Issue by Shashengzhe** [deepjavalibrary/djl#2283] opened 2023-01-04 03:41 UTC
## Description
PtNDArray.get(NDArray index)和PtNDArray.set(NDIndex index, NDArray value) cause memory leak

### Expected Behavior
(what's the expected behavior?)

### Error Message
memory leak

## How to Reproduce?
try (final NDManager ndManager = NDManager.newBaseManager()) {
            while (true) {
                try (NDManager manager = ndManager.newSubManager()) {
                    NDArray a = manager.create(new int[1024 * 1024 * 1]);
                    final NDArray eq = a.eq(1);
                    a.get(eq);
                }
            }
        }

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. 
2.

## What have you tried to solve it?

1. add a method to delete index memory which created by method ai.djl.pytorch.jni.PyTorchLibrary#torchIndexInit
2.

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
PASTE OUTPUT HERE
```

**Comment by frankfliu** [comment] 2023-01-04 04:18
This is duplicate of: #2281

**Closed** 2023-01-06 19:57 UTC
Labels: bug
